### ISSUE TITLE
New chips for world 4 (and world 3.5 ??)

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#160]
New chip list! Whoo!

Stuff we'll need:
 - [x] Map crater lower chip (a texture, expect to see it spammed about as much as the default FFL1 this-terrain-leads-to-wilderness thing)
 - [x] Ruined city upper chip (a few of them for variety maybe?)
 - [x] Maybe a desert chip? We sort of have a rocky terrain thing I've been using near mountains but I think a nuclear wasteland needs a legit desert.

Stuff it'd good to have:

 - [x] At least one new town wall and ceiling tile... not sure what they should be really but just need something to make the cities stand out
 - [x] A new cave interior wall and ceiling tile (even if the ceiling is just a dark version of the wall) (see above)
 - [ ] Some sort of spammable "junk" upper chip

Stuff it'd be cool to have:

We'll probably need to expand on this as we come up with the plotlines for worlds 3.5 and 4, but I know we'll need these at a minimum. Especially the craters should be high priority for the world 3.5 overworld.

**Comment by crumley467** [comment]
As the neo-japan theme was scrapped from world 3 when we replaced it with "future-ish," is neo-japan making a comeback? If memory serves, its going to be towns full of mutants on the overworld and humans below ground. In this case, since its a nuclear wasteland, I think it would be somewhat appropriate that we had a japanese theme going with the remaining habitable structures on the overworld.

**Comment by psywombats** [comment]
I think everything's vaguely Japan-ish (gates, Hatamotos, etc) so maybe we just add a bit of that flavor in every world rather than having one designated Japan-world.

**Comment by psywombats** [comment]
Upload when you can, would like to get mapping W3
