### ISSUE TITLE
It is possible to get multiple stacks of paralysis?

### ISSUE THREAD

**Issue by crumley467** [psywombats/mgne#189]
My robot was paralyzed twice in the same round, and in stead of saying "Nothing happened" it said "BORGSLY is paralyzed" and at the end of the round i got two "BORGSLY is paralyzed" messages.

**Comment by psywombats** [comment]
I went back and forth on this, but I think it's decent behavior. If we said "nothing happened" for the hit, people might think BORGSLY had resisted paralysis when really he's actually paralyzed, and I'd rather not add an explicit message for "is already" etc. 

The two messages at the end of the round was a status message (reminding who has what status) and a you-can't-act message (coming last because apparently he is slow)
