### ISSUE TITLE
Round 1 playtesting: default party

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#196]
Finish this up and then round 1's done.

**Comment by crumley467** [comment]
All said and done. Buffed robots and a healthy helping of NUKE/mirror glove/ribbon did the job.
Hardest fight: Lucifer
Fight with JORGANDR2 and FENRIR2 was dead easy, SHIVA2 was tricky
Tiger Cave is ass, nothing to do with my party
Ended up fighting MACHINE and MOLOCH only to have just Steve with O-ALL survive. A little more thought in terms of my monsters, as well as healing items, would have had to go into the fights. 
Adding something to the bazaar to grant blind immunity would have been nice, because that's primarily what made that fight ass for me. Or even just an eyedrop as a cheaper alternative to x-cure.
