### ISSUE TITLE
Support uninterrupted map/battle BGM playback

### ISSUE THREAD

**Issue by psywombats** [psywombats/mgne#523]
Locations where battle bgm shouldn't interrupt field music:
 - research lab
 - missile base

**Comment by SkankinGarbage** [comment]
Were you, by chance, working on this task? Because the current build sort of does this at the moment:

- If you complete a battle, the victory theme continues to play after going back to the map, until the next BGM change.

- If you run from a battle, the battle theme persists until the next BGM change; getting into another battle does not restart the track. 

Just in case this was a bug, I thought you might like to know about it, since however it's working right now is almost the correct implementation of this feature. But, also, it's like this everywhere instead of the one or two places we actually want it, so it's a little weird right now.

**Comment by psywombats** [comment]
I hadn't worked on this, but it should be working now. The implementation I'm going with still plays the victory/defeat bgm. Not sure if that's the best way to do it, but it seems weird otherwise.
