### ISSUE TITLE
Design: Monsters could use more typeless damage at tier 12

### ISSUE THREAD

**Issue by SkankinGarbage** [psywombats/mgne#730]
I had 850000 gold and spent all of it getting four monsters that could actually hang against Moloch. Lots of monsters at that tier can barely even deal damage to Moloch, and the ones that can usually have very low charges on their moves (e.g Golem). My suggestion would be to give beam to Sylph as well, but that might be a lazy option since Undine has that. It's just difficult to outlast Moloch with his current design, even if you have heals.

**Comment by SkankinGarbage** [comment]
I meant to write about this a bit more, but I forgot. There's one main thing that has changed that makes the fight harder for a four monster group since I last tried it in earlier times, and that's CHAR. I used to be able to handle this fight pretty well with Undine, but since they are weak to fire, they now have a chance to be suddenly instant-killed.

So, the issue may not be a lack of typeless damage (although it could certainly help), so much as it is that the threat of the best monsters for the job being OHKO'd makes it hard to beat Moloch without stunlocks (which I know we are planning to make harder to do).

**Comment by psywombats** [comment]
I've removed x-fire from UNDINE (why are water elves weak to fire??).

Interested if you tried T-CELL at all, which has ARMOR for this fight to provide a lot more beefiness in the face of NUKE, plus DISSOLVE to hit through O-ALL. It's also weak to fire, which makes me think probably not. CHAR was more supposed to be a reward for humans wearing O-FIRE equipment more than a punishment for monsters, so I've also just removed its ability to critically hit (because X-FIRE is common to all disease enemies for balance reasons w/ deathskin).

MUMMY is also available with two sources of typeless drain damage... and again it had X-FIRE, ugh. I really want to keep that for flavor reasons. Hopefully dropping CHAR's crit solves this. Threw STENCH on Mummy to give it more utility for this fight in case its drains run out.

If I were making a monster team for this fight now, I'd run with T-CELL / MUMMY / UNDINE / KI-RIN .
